openapi: "3.0.0"
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /cep-search/{cep}:
    get:
      summary: Returns address by on zip code.
      description: Returns address by on zip code.
      parameters:
        - in: path
          name: cep
          schema:
            type: string
          required: true
          description: Numeric ID of the user to get
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EddressResponse"
components:
  schemas:
    EddressResponse:
      type: object
      properties:
        Street:
          type: string
        district:
          type: string
        state:
          type: string
        city:
          type: string
        cep:
          type: string