openapi: "3.0.0"
info:
  title: Address API
  description: Consult address by zip code.
  version: 0.1.9
paths:
  /search/{zipcode}:
    get:
      summary: Returns address by on zip code.
      description: Returns address by on zip code.
      parameters:
        - in: path
          name: zipcode
          schema:
            type: string
          required: true
          description: Numeric zip code
      responses:
        "200":
          description: A JSON array of address
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddressResponse"
        404:
          description: A address with the specified zipcode was not found.
components:
  schemas:
    AddressResponse:
      type: object
      properties:
        street:
          type: string
        district:
          type: string
        state:
          type: string
        city:
          type: string
        cep:
          type: string